### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by moltar** [MShekow/directory-checksum#45]
Hi Marius,

I cannot get this tool to work for my life.

I tried all kinds of builds and releases across local macOS (ARM) and remote CI (CodeBuild, x86-64) and every time, the tool prints nothing and no error code on exit.

For example, here's how I ran it on CodeBuild:

```sh
curl --output /usr/local/bin/directory-checksum https://github.com/MShekow/directory-checksum/releases/download/v1.4.4/directory-checksum_1.4.4_linux_amd64
curl --output /usr/local/bin/directory-checksum https://github.com/MShekow/directory-checksum/releases/download/v1.4.4/directory-checksum_1.4.4_linux_amd64
directory-checksum --max-depth 2 .
```

The output is:

```
[Container] 2024/10/04 10:24:52.592451 Running command directory-checksum --max-depth 2 .

[Container] 2024/10/04 10:24:52.604295 Running command docker buildx build
```

The dir for sure has the files, as it is a git checked out src dir, and subsequent Docker build works fine.

**Comment by MShekow** [comment]
I'm sorry. No idea. You should run directory-checksum inside a container anyway, and follow the instructions of the README _to the letter_, including "chmod +x" (which you don't show in your snippet, so it cannot possibly work).
